### ISSUE TITLE
a little mistake in google code labs tutorial

### ISSUE THREAD

**Issue by saqibsoftwares** [googlecodelabs/admob-native-advanced-feed#1]
On step number 12, 
```
<resources>
   ...
   <string name="admob_app_id">ca-app-pub-3940256099942544/8135179316</string>
   ...
</resources>
```

 "admob_app_id" should be "ad_unit_id" because it's ad id and app ID has already been defined in previous step.

This may save some time of beginners.

**Comment by ericleich** [comment]
This is fixed now. Great catch, and sorry this took so long to fix!
