### ISSUE TITLE
Use of undeclared type 'GADUnifiedNativeAdLoaderDelegate'

### ISSUE THREAD

**Issue by Tapaniya25** [googlecodelabs/admob-native-advanced-feed#8]
I am trying to make a demo of this ads. While i follow [this](https://codelabs.developers.google.com/codelabs/admob-native-advanced-feed-ios/index.html#0) tutorial. Getting this error **Use of undeclared type 'GADUnifiedNativeAdLoaderDelegate'**. 
I am using the latest version of GoogleMobileAds.framework.

**Comment by stowy** [comment]
That doesn't sound correct. `GADUnifiedNativeAdLoaderDelegate` is part of the framework as of Google-Mobile-Ads-SDK [version 7.28.0](https://developers.google.com/admob/ios/rel-notes) - here's the reference docs - https://developers.google.com/admob/ios/api/reference/Protocols/GADUnifiedNativeAdLoaderDelegate.

Are you sure you have at least version 7.28.0 installed? You can check by calling `[GADRequest SDKVersion]` [as documented here.](https://developers.google.com/admob/ios/api/reference/Classes/GADRequest#sdkversion)

**Comment by Tapaniya25** [comment]
Sorry, I am using an older version(7.25.0) of Admob. The latest one is 7.29.0. When i have written pod 'Firebase/AdMob' in podfile at that time i got version 7.25.0. Then after i write pod 'Google-Mobile-Ads-SDK' so i got 7.29.0 version of AdMob.
